//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatToursManager.DAL
{
    using System;
    using System.Collections.Generic;
    public partial class BoatToursManager
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoatToursManager()
        {
            this.Orders = new HashSet<Order>();
            this.Locations = new HashSet<Location>();
            this.PersonCategories = new HashSet<PersonCategory>();
            this.PriceCategories = new HashSet<PriceCategory>();
            this.Routes = new HashSet<Route>();
            this.SchedulePlans = new HashSet<SchedulePlan>();
            this.Ships = new HashSet<Ship>();
            this.TripTypes = new HashSet<TripType>();
            this.Users = new HashSet<User>();
        }

        public int id { get; set; }
        public int numOrders { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Location> Locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PersonCategory> PersonCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PriceCategory> PriceCategories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Route> Routes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SchedulePlan> SchedulePlans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ship> Ships { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TripType> TripTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
    //public partial class BoatToursManager
    //{
    //    public int id { get; set; }
    //    public Nullable<int> locationId { get; set; }
    //    public Nullable<int> routeId { get; set; }
    //    public Nullable<int> schedulePlanId { get; set; }
    //    public Nullable<int> orderId { get; set; }
    //    public Nullable<int> shipId { get; set; }

    //    public virtual BoatToursManager BoatToursManager1 { get; set; }
    //    public virtual BoatToursManager BoatToursManager2 { get; set; }
    //    public virtual Location Location { get; set; }
    //    public virtual Order Order { get; set; }
    //    public virtual Route Route { get; set; }
    //    public virtual SchedulePlan SchedulePlan { get; set; }
    //    public virtual Ship Ship { get; set; }
    //}
}
