//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatToursManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupTripPriceCategory
    {
        public int price_category_id { get; set; }
        public int group_trip_id { get; set; }
        public int quantity { get; set; }
    
        public virtual GroupTrip GroupTrip { get; set; }
        public virtual PriceCategory PriceCategory { get; set; }
    }
}
