//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatToursManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LikeDislikeBoat
    {
        public int id { get; set; }
        public int boatId { get; set; }
        public int userid { get; set; }
        public int action { get; set; }
        public bool isLike { get; set; }
    
        public virtual Boat Boat { get; set; }
        public virtual User User { get; set; }
    }
}
