//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatToursManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.BoatToursManager = new HashSet<BoatToursManager>();
        }
    
        public int id { get; set; }
        public Nullable<int> addressId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<int> paymentType { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
        public Nullable<bool> billed { get; set; }
        public Nullable<int> orderNumber { get; set; }
        public Nullable<double> price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoatToursManager> BoatToursManager { get; set; }
        public virtual UserAddress UserAddress { get; set; }
        public virtual User User { get; set; }
        public virtual BoatRental BoatRental { get; set; }
        public virtual GroupTrip GroupTrip { get; set; }
    }
}
