//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatToursManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PriceCategory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PriceCategory()
        {
            this.GroupTripPriceCategory = new HashSet<GroupTripPriceCategory>();
        }
    
        public int id { get; set; }
        public int tripTypeId { get; set; }
        public int personCategoryId { get; set; }
        public int routeId { get; set; }
        public string name { get; set; }
        public decimal price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTripPriceCategory> GroupTripPriceCategory { get; set; }
        public virtual PersonCategory PersonCategory { get; set; }
        public virtual TripType TripType { get; set; }
    }
}
