//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BoatToursManager.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Route()
        {
            this.BoatToursManager = new HashSet<BoatToursManager>();
            this.GroupTrip = new HashSet<GroupTrip>();
        }
    
        public int id { get; set; }
        public int startPointLatLengId { get; set; }
        public int endPointLatLengId { get; set; }
        public decimal driveTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoatToursManager> BoatToursManager { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GroupTrip> GroupTrip { get; set; }
        public virtual LatLongCoordinate LatLongCoordinate { get; set; }
        public virtual LatLongCoordinate LatLongCoordinate1 { get; set; }
        public virtual Route Route1 { get; set; }
        public virtual Route Route2 { get; set; }
        public virtual ScheduleRoute ScheduleRoute { get; set; }
    }
}
